version: '3'

services:
  traefik:
    # The latest official supported Traefik docker image
    image: traefik:v2.10
    # Enables the Traefik Dashboard and tells Traefik to listen to docker
    # enable --log.level=INFO so we can see what Traefik is doing in the log files
    ports:
      # Exposes port 80 for incomming web requests
      - "80:80"
      - "443:443"
      # The Web UI port http://0.0.0.0:8080 (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      # Copies the Let's Encrypt certificate locally for ease of backing up
      - ./letsencrypt:/letsencrypt
      # Mounts the Traefik static configuration inside the Traefik container
      - ./traefik.dns.yml:/etc/traefik/traefik.yml
    env_file:
      - ./.env

  catapp:
    image: mikesir87/cats:1.0
    labels:
      - "traefik.enable=true"
      #routers
      - "traefik.http.routers.catapp.rule=Host(`redirect.hybriddev.de`)"
      - "traefik.http.routers.catapp.entrypoints=web"
      - "traefik.http.routers.catapp.middlewares=midd-redirect"

      - "traefik.http.routers.catapp-secure.rule=Host(`redirect.hybriddev.de`)"
      - "traefik.http.routers.catapp-secure.service=catapp"
      - "traefik.http.routers.catapp-secure.entrypoints=websecure"
      - "traefik.http.routers.catapp-secure.tls.certresolver=dnsResolver"
      - "traefik.http.routers.catapp-secure.middlewares=midd-compress,midd-error,midd-rate"
      #services
      - "traefik.http.services.catapp.loadbalancer.server.port=5000"
      #midd
        # compress
      - "traefik.http.middlewares.midd-compress.compress=true"
        # error
      - "traefik.http.middlewares.midd-error.errors.status=400-599"
      - "traefik.http.middlewares.midd-error.errors.service=error"
      - "traefik.http.middlewares.midd-error.errors.query=/{status}.html"
        # rate limit
      - "traefik.http.middlewares.midd-rate.ratelimit.average=4"
        # redirect
      - "traefik.http.middlewares.midd-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.midd-redirect.redirectscheme.permanent=true"


  error:
    image: guillaumebriday/traefik-custom-error-pages
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.error.rule=Host(`error.localhost`)"
      - "traefik.http.routers.error.service=error"
      - "traefik.http.services.error.loadbalancer.server.port=80"
      - "traefik.http.routers.error.entrypoints=web"
